/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  DeliveryScheduleIssue as PrismaDeliveryScheduleIssue,
} from "@prisma/client";

export class DeliveryScheduleIssueServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DeliveryScheduleIssueCountArgs, "select">
  ): Promise<number> {
    return this.prisma.deliveryScheduleIssue.count(args);
  }

  async deliveryScheduleIssues(
    args: Prisma.DeliveryScheduleIssueFindManyArgs
  ): Promise<PrismaDeliveryScheduleIssue[]> {
    return this.prisma.deliveryScheduleIssue.findMany(args);
  }
  async deliveryScheduleIssue(
    args: Prisma.DeliveryScheduleIssueFindUniqueArgs
  ): Promise<PrismaDeliveryScheduleIssue | null> {
    return this.prisma.deliveryScheduleIssue.findUnique(args);
  }
  async createDeliveryScheduleIssue(
    args: Prisma.DeliveryScheduleIssueCreateArgs
  ): Promise<PrismaDeliveryScheduleIssue> {
    return this.prisma.deliveryScheduleIssue.create(args);
  }
  async updateDeliveryScheduleIssue(
    args: Prisma.DeliveryScheduleIssueUpdateArgs
  ): Promise<PrismaDeliveryScheduleIssue> {
    return this.prisma.deliveryScheduleIssue.update(args);
  }
  async deleteDeliveryScheduleIssue(
    args: Prisma.DeliveryScheduleIssueDeleteArgs
  ): Promise<PrismaDeliveryScheduleIssue> {
    return this.prisma.deliveryScheduleIssue.delete(args);
  }
}
